/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignatureRouteImport } from './routes/signature'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSubmissionsRouteImport } from './routes/admin/submissions'
import { Route as AdminSiteRouteImport } from './routes/admin/site'
import { Route as AdminSectionsRouteImport } from './routes/admin/sections'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminNavRouteImport } from './routes/admin/nav'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminBenefitsRouteImport } from './routes/admin/benefits'

const SignatureRoute = SignatureRouteImport.update({
  id: '/signature',
  path: '/signature',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSiteRoute = AdminSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSectionsRoute = AdminSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNavRoute = AdminNavRouteImport.update({
  id: '/nav',
  path: '/nav',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBenefitsRoute = AdminBenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/locations': typeof LocationsRoute
  '/menu': typeof MenuRoute
  '/signature': typeof SignatureRoute
  '/admin/benefits': typeof AdminBenefitsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/nav': typeof AdminNavRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/locations': typeof LocationsRoute
  '/menu': typeof MenuRoute
  '/signature': typeof SignatureRoute
  '/admin/benefits': typeof AdminBenefitsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/nav': typeof AdminNavRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/locations': typeof LocationsRoute
  '/menu': typeof MenuRoute
  '/signature': typeof SignatureRoute
  '/admin/benefits': typeof AdminBenefitsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/nav': typeof AdminNavRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/locations'
    | '/menu'
    | '/signature'
    | '/admin/benefits'
    | '/admin/login'
    | '/admin/media'
    | '/admin/nav'
    | '/admin/products'
    | '/admin/sections'
    | '/admin/site'
    | '/admin/submissions'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/locations'
    | '/menu'
    | '/signature'
    | '/admin/benefits'
    | '/admin/login'
    | '/admin/media'
    | '/admin/nav'
    | '/admin/products'
    | '/admin/sections'
    | '/admin/site'
    | '/admin/submissions'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/locations'
    | '/menu'
    | '/signature'
    | '/admin/benefits'
    | '/admin/login'
    | '/admin/media'
    | '/admin/nav'
    | '/admin/products'
    | '/admin/sections'
    | '/admin/site'
    | '/admin/submissions'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ContactRoute: typeof ContactRoute
  LocationsRoute: typeof LocationsRoute
  MenuRoute: typeof MenuRoute
  SignatureRoute: typeof SignatureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signature': {
      id: '/signature'
      path: '/signature'
      fullPath: '/signature'
      preLoaderRoute: typeof SignatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/site': {
      id: '/admin/site'
      path: '/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AdminSiteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sections': {
      id: '/admin/sections'
      path: '/sections'
      fullPath: '/admin/sections'
      preLoaderRoute: typeof AdminSectionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/nav': {
      id: '/admin/nav'
      path: '/nav'
      fullPath: '/admin/nav'
      preLoaderRoute: typeof AdminNavRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/benefits': {
      id: '/admin/benefits'
      path: '/benefits'
      fullPath: '/admin/benefits'
      preLoaderRoute: typeof AdminBenefitsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminBenefitsRoute: typeof AdminBenefitsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNavRoute: typeof AdminNavRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSectionsRoute: typeof AdminSectionsRoute
  AdminSiteRoute: typeof AdminSiteRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBenefitsRoute: AdminBenefitsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNavRoute: AdminNavRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSectionsRoute: AdminSectionsRoute,
  AdminSiteRoute: AdminSiteRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ContactRoute: ContactRoute,
  LocationsRoute: LocationsRoute,
  MenuRoute: MenuRoute,
  SignatureRoute: SignatureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
