import type { CareFlowDatabase } from './careflow-types'

const now = '2026-05-26T07:00:00.000Z'

export const initialCareFlowDatabase: CareFlowDatabase = {
  user: {
    id: 'patient-diane-lara',
    name: 'Diane Lara',
    age: 29,
    email: 'diane.lara@example.com',
    phone: '+1 555 019 3371',
    avatarUrl:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=160&q=80',
    carePlan: 'Free',
  },
  appointments: [
    {
      id: 'appt-cardiology-2025-10-14',
      specialist: 'Cardiologist',
      doctorName: 'Dr. Mason Reed',
      date: '2025-10-14',
      time: '14:00',
      reason: 'General Consultation',
      paymentStatus: 'Paid',
      status: 'Scheduled',
      notes: 'Review heart rate trends and family history.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'appt-endocrinology-2025-10-19',
      specialist: 'Endocrinologist',
      doctorName: 'Dr. Lina Brooks',
      date: '2025-10-19',
      time: '10:30',
      reason: 'Follow-up',
      paymentStatus: 'Unpaid',
      status: 'Scheduled',
      notes: 'Discuss blood glucose reading stability.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'appt-dermatology-2025-10-20',
      specialist: 'Dermatologist',
      doctorName: 'Dr. Scarlet Everett',
      date: '2025-10-20',
      time: '13:30',
      reason: 'Test Results Review',
      paymentStatus: 'Insurance',
      status: 'Scheduled',
      notes: 'Insurance authorization already attached.',
      createdAt: now,
      updatedAt: now,
    },
  ],
  consultations: [
    {
      id: 'consult-live-scarlet-everett',
      doctorName: 'Ian Katana',
      specialty: 'Lead Software Developer',
      duration: '02:15:43',
      status: 'Live',
      appointmentId: 'appt-dermatology-2025-10-20',
      startedAt: now,
      patientVideoEnabled: true,
      patientMicEnabled: true,
    },
  ],
  conversations: [
    {
      id: 'thread-care-team',
      title: 'Care plan follow-up',
      doctorName: 'CareFlow Team',
      specialty: 'Care Team',
      status: 'Open',
      createdAt: now,
      updatedAt: now,
      messages: [
        {
          id: 'msg-care-team-1',
          sender: 'Care Team',
          body: 'Your October consultations are confirmed. Please keep logging your daily vitals.',
          sentAt: now,
          read: true,
        },
        {
          id: 'msg-care-team-2',
          sender: 'Patient',
          body: 'Thank you. I uploaded notes about the glucose reading change.',
          sentAt: now,
          read: true,
        },
      ],
    },
    {
      id: 'thread-dr-everett',
      title: 'Skin test results',
      doctorName: 'Dr. Scarlet Everett',
      specialty: 'Dermatology',
      status: 'Open',
      createdAt: now,
      updatedAt: now,
      messages: [
        {
          id: 'msg-everett-1',
          sender: 'Doctor',
          body: 'The first result set is reassuring. We can discuss the next care step in the video call.',
          sentAt: now,
          read: false,
        },
      ],
    },
  ],
  healthMetrics: [
    {
      id: 'metric-2025-10-03',
      date: '2025-10-03',
      weightKg: 61,
      heartRateBpm: 74,
      bloodGlucoseMmol: 4.8,
      systolic: 118,
      diastolic: 76,
      oxygenSaturation: 98,
      notes: 'Mild afternoon fatigue.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'metric-2025-10-07',
      date: '2025-10-07',
      weightKg: 59,
      heartRateBpm: 71,
      bloodGlucoseMmol: 4.6,
      systolic: 116,
      diastolic: 75,
      oxygenSaturation: 99,
      notes: 'Post-walk reading.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'metric-2025-10-09',
      date: '2025-10-09',
      weightKg: 74,
      heartRateBpm: 70,
      bloodGlucoseMmol: 4.5,
      systolic: 115,
      diastolic: 74,
      oxygenSaturation: 99,
      notes: 'Baseline feels stable.',
      createdAt: now,
      updatedAt: now,
    },
  ],
  subscription: {
    plan: 'Free',
    renewsAt: '2025-11-09',
    priorityConsultations: false,
    personalizedGuidance: false,
  },
}
