/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as AuthenticatedViewingsRouteImport } from './routes/_authenticated/viewings'
import { Route as AuthenticatedTenantsRouteImport } from './routes/_authenticated/tenants'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRenewalsRouteImport } from './routes/_authenticated/renewals'
import { Route as AuthenticatedPropertiesRouteImport } from './routes/_authenticated/properties'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComplaintsRouteImport } from './routes/_authenticated/complaints'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedTenantsIndexRouteImport } from './routes/_authenticated/tenants.index'
import { Route as AuthenticatedPropertiesIndexRouteImport } from './routes/_authenticated/properties.index'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal.index'
import { Route as AuthenticatedPaymentsIndexRouteImport } from './routes/_authenticated/payments.index'
import { Route as AuthenticatedMaintenanceIndexRouteImport } from './routes/_authenticated/maintenance.index'
import { Route as AuthenticatedComplaintsIndexRouteImport } from './routes/_authenticated/complaints.index'
import { Route as AuthenticatedApplicationsIndexRouteImport } from './routes/_authenticated/applications.index'
import { Route as AuthenticatedTenantsIdRouteImport } from './routes/_authenticated/tenants.$id'
import { Route as AuthenticatedPropertiesIdRouteImport } from './routes/_authenticated/properties.$id'
import { Route as AuthenticatedPortalProfileRouteImport } from './routes/_authenticated/portal.profile'
import { Route as AuthenticatedPeopleIdRouteImport } from './routes/_authenticated/people.$id'
import { Route as AuthenticatedPaymentsIdRouteImport } from './routes/_authenticated/payments.$id'
import { Route as AuthenticatedMaintenanceIdRouteImport } from './routes/_authenticated/maintenance.$id'
import { Route as AuthenticatedComplaintsIdRouteImport } from './routes/_authenticated/complaints.$id'
import { Route as AuthenticatedApplicationsIdRouteImport } from './routes/_authenticated/applications.$id'
import { Route as AuthenticatedPortalApplicationsIdRouteImport } from './routes/_authenticated/portal.applications.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ListingsRoute,
} as any)
const AuthenticatedViewingsRoute = AuthenticatedViewingsRouteImport.update({
  id: '/viewings',
  path: '/viewings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenantsRoute = AuthenticatedTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRenewalsRoute = AuthenticatedRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropertiesRoute = AuthenticatedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplaintsRoute = AuthenticatedComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTenantsIndexRoute =
  AuthenticatedTenantsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTenantsRoute,
  } as any)
const AuthenticatedPropertiesIndexRoute =
  AuthenticatedPropertiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPropertiesRoute,
  } as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPaymentsIndexRoute =
  AuthenticatedPaymentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPaymentsRoute,
  } as any)
const AuthenticatedMaintenanceIndexRoute =
  AuthenticatedMaintenanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMaintenanceRoute,
  } as any)
const AuthenticatedComplaintsIndexRoute =
  AuthenticatedComplaintsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedComplaintsRoute,
  } as any)
const AuthenticatedApplicationsIndexRoute =
  AuthenticatedApplicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedApplicationsRoute,
  } as any)
const AuthenticatedTenantsIdRoute = AuthenticatedTenantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTenantsRoute,
} as any)
const AuthenticatedPropertiesIdRoute =
  AuthenticatedPropertiesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPropertiesRoute,
  } as any)
const AuthenticatedPortalProfileRoute =
  AuthenticatedPortalProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPeopleIdRoute = AuthenticatedPeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsIdRoute = AuthenticatedPaymentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPaymentsRoute,
} as any)
const AuthenticatedMaintenanceIdRoute =
  AuthenticatedMaintenanceIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedMaintenanceRoute,
  } as any)
const AuthenticatedComplaintsIdRoute =
  AuthenticatedComplaintsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedComplaintsRoute,
  } as any)
const AuthenticatedApplicationsIdRoute =
  AuthenticatedApplicationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedApplicationsRoute,
  } as any)
const AuthenticatedPortalApplicationsIdRoute =
  AuthenticatedPortalApplicationsIdRouteImport.update({
    id: '/applications/$id',
    path: '/applications/$id',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/listings': typeof ListingsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/complaints': typeof AuthenticatedComplaintsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/maintenance': typeof AuthenticatedMaintenanceRouteWithChildren
  '/payments': typeof AuthenticatedPaymentsRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/properties': typeof AuthenticatedPropertiesRouteWithChildren
  '/renewals': typeof AuthenticatedRenewalsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tenants': typeof AuthenticatedTenantsRouteWithChildren
  '/viewings': typeof AuthenticatedViewingsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/complaints/$id': typeof AuthenticatedComplaintsIdRoute
  '/maintenance/$id': typeof AuthenticatedMaintenanceIdRoute
  '/payments/$id': typeof AuthenticatedPaymentsIdRoute
  '/people/$id': typeof AuthenticatedPeopleIdRoute
  '/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/properties/$id': typeof AuthenticatedPropertiesIdRoute
  '/tenants/$id': typeof AuthenticatedTenantsIdRoute
  '/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/complaints/': typeof AuthenticatedComplaintsIndexRoute
  '/maintenance/': typeof AuthenticatedMaintenanceIndexRoute
  '/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/tenants/': typeof AuthenticatedTenantsIndexRoute
  '/portal/applications/$id': typeof AuthenticatedPortalApplicationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/listings': typeof ListingsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/renewals': typeof AuthenticatedRenewalsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/viewings': typeof AuthenticatedViewingsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/complaints/$id': typeof AuthenticatedComplaintsIdRoute
  '/maintenance/$id': typeof AuthenticatedMaintenanceIdRoute
  '/payments/$id': typeof AuthenticatedPaymentsIdRoute
  '/people/$id': typeof AuthenticatedPeopleIdRoute
  '/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/properties/$id': typeof AuthenticatedPropertiesIdRoute
  '/tenants/$id': typeof AuthenticatedTenantsIdRoute
  '/applications': typeof AuthenticatedApplicationsIndexRoute
  '/complaints': typeof AuthenticatedComplaintsIndexRoute
  '/maintenance': typeof AuthenticatedMaintenanceIndexRoute
  '/payments': typeof AuthenticatedPaymentsIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/properties': typeof AuthenticatedPropertiesIndexRoute
  '/tenants': typeof AuthenticatedTenantsIndexRoute
  '/portal/applications/$id': typeof AuthenticatedPortalApplicationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/listings': typeof ListingsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRouteWithChildren
  '/_authenticated/complaints': typeof AuthenticatedComplaintsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRouteWithChildren
  '/_authenticated/payments': typeof AuthenticatedPaymentsRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/_authenticated/properties': typeof AuthenticatedPropertiesRouteWithChildren
  '/_authenticated/renewals': typeof AuthenticatedRenewalsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tenants': typeof AuthenticatedTenantsRouteWithChildren
  '/_authenticated/viewings': typeof AuthenticatedViewingsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/_authenticated/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/_authenticated/complaints/$id': typeof AuthenticatedComplaintsIdRoute
  '/_authenticated/maintenance/$id': typeof AuthenticatedMaintenanceIdRoute
  '/_authenticated/payments/$id': typeof AuthenticatedPaymentsIdRoute
  '/_authenticated/people/$id': typeof AuthenticatedPeopleIdRoute
  '/_authenticated/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/_authenticated/properties/$id': typeof AuthenticatedPropertiesIdRoute
  '/_authenticated/tenants/$id': typeof AuthenticatedTenantsIdRoute
  '/_authenticated/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/_authenticated/complaints/': typeof AuthenticatedComplaintsIndexRoute
  '/_authenticated/maintenance/': typeof AuthenticatedMaintenanceIndexRoute
  '/_authenticated/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/properties/': typeof AuthenticatedPropertiesIndexRoute
  '/_authenticated/tenants/': typeof AuthenticatedTenantsIndexRoute
  '/_authenticated/portal/applications/$id': typeof AuthenticatedPortalApplicationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/listings'
    | '/reset-password'
    | '/agents'
    | '/applications'
    | '/complaints'
    | '/dashboard'
    | '/maintenance'
    | '/payments'
    | '/portal'
    | '/properties'
    | '/renewals'
    | '/settings'
    | '/tenants'
    | '/viewings'
    | '/listings/$id'
    | '/applications/$id'
    | '/complaints/$id'
    | '/maintenance/$id'
    | '/payments/$id'
    | '/people/$id'
    | '/portal/profile'
    | '/properties/$id'
    | '/tenants/$id'
    | '/applications/'
    | '/complaints/'
    | '/maintenance/'
    | '/payments/'
    | '/portal/'
    | '/properties/'
    | '/tenants/'
    | '/portal/applications/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/listings'
    | '/reset-password'
    | '/agents'
    | '/dashboard'
    | '/renewals'
    | '/settings'
    | '/viewings'
    | '/listings/$id'
    | '/applications/$id'
    | '/complaints/$id'
    | '/maintenance/$id'
    | '/payments/$id'
    | '/people/$id'
    | '/portal/profile'
    | '/properties/$id'
    | '/tenants/$id'
    | '/applications'
    | '/complaints'
    | '/maintenance'
    | '/payments'
    | '/portal'
    | '/properties'
    | '/tenants'
    | '/portal/applications/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/listings'
    | '/reset-password'
    | '/_authenticated/agents'
    | '/_authenticated/applications'
    | '/_authenticated/complaints'
    | '/_authenticated/dashboard'
    | '/_authenticated/maintenance'
    | '/_authenticated/payments'
    | '/_authenticated/portal'
    | '/_authenticated/properties'
    | '/_authenticated/renewals'
    | '/_authenticated/settings'
    | '/_authenticated/tenants'
    | '/_authenticated/viewings'
    | '/listings/$id'
    | '/_authenticated/applications/$id'
    | '/_authenticated/complaints/$id'
    | '/_authenticated/maintenance/$id'
    | '/_authenticated/payments/$id'
    | '/_authenticated/people/$id'
    | '/_authenticated/portal/profile'
    | '/_authenticated/properties/$id'
    | '/_authenticated/tenants/$id'
    | '/_authenticated/applications/'
    | '/_authenticated/complaints/'
    | '/_authenticated/maintenance/'
    | '/_authenticated/payments/'
    | '/_authenticated/portal/'
    | '/_authenticated/properties/'
    | '/_authenticated/tenants/'
    | '/_authenticated/portal/applications/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ListingsRoute: typeof ListingsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof ListingsRoute
    }
    '/_authenticated/viewings': {
      id: '/_authenticated/viewings'
      path: '/viewings'
      fullPath: '/viewings'
      preLoaderRoute: typeof AuthenticatedViewingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenants': {
      id: '/_authenticated/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthenticatedTenantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/renewals': {
      id: '/_authenticated/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof AuthenticatedRenewalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties': {
      id: '/_authenticated/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthenticatedPropertiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complaints': {
      id: '/_authenticated/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AuthenticatedComplaintsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenants/': {
      id: '/_authenticated/tenants/'
      path: '/'
      fullPath: '/tenants/'
      preLoaderRoute: typeof AuthenticatedTenantsIndexRouteImport
      parentRoute: typeof AuthenticatedTenantsRoute
    }
    '/_authenticated/properties/': {
      id: '/_authenticated/properties/'
      path: '/'
      fullPath: '/properties/'
      preLoaderRoute: typeof AuthenticatedPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedPropertiesRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/payments/': {
      id: '/_authenticated/payments/'
      path: '/'
      fullPath: '/payments/'
      preLoaderRoute: typeof AuthenticatedPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedPaymentsRoute
    }
    '/_authenticated/maintenance/': {
      id: '/_authenticated/maintenance/'
      path: '/'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof AuthenticatedMaintenanceIndexRouteImport
      parentRoute: typeof AuthenticatedMaintenanceRoute
    }
    '/_authenticated/complaints/': {
      id: '/_authenticated/complaints/'
      path: '/'
      fullPath: '/complaints/'
      preLoaderRoute: typeof AuthenticatedComplaintsIndexRouteImport
      parentRoute: typeof AuthenticatedComplaintsRoute
    }
    '/_authenticated/applications/': {
      id: '/_authenticated/applications/'
      path: '/'
      fullPath: '/applications/'
      preLoaderRoute: typeof AuthenticatedApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedApplicationsRoute
    }
    '/_authenticated/tenants/$id': {
      id: '/_authenticated/tenants/$id'
      path: '/$id'
      fullPath: '/tenants/$id'
      preLoaderRoute: typeof AuthenticatedTenantsIdRouteImport
      parentRoute: typeof AuthenticatedTenantsRoute
    }
    '/_authenticated/properties/$id': {
      id: '/_authenticated/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof AuthenticatedPropertiesIdRouteImport
      parentRoute: typeof AuthenticatedPropertiesRoute
    }
    '/_authenticated/portal/profile': {
      id: '/_authenticated/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof AuthenticatedPortalProfileRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/people/$id': {
      id: '/_authenticated/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof AuthenticatedPeopleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/$id': {
      id: '/_authenticated/payments/$id'
      path: '/$id'
      fullPath: '/payments/$id'
      preLoaderRoute: typeof AuthenticatedPaymentsIdRouteImport
      parentRoute: typeof AuthenticatedPaymentsRoute
    }
    '/_authenticated/maintenance/$id': {
      id: '/_authenticated/maintenance/$id'
      path: '/$id'
      fullPath: '/maintenance/$id'
      preLoaderRoute: typeof AuthenticatedMaintenanceIdRouteImport
      parentRoute: typeof AuthenticatedMaintenanceRoute
    }
    '/_authenticated/complaints/$id': {
      id: '/_authenticated/complaints/$id'
      path: '/$id'
      fullPath: '/complaints/$id'
      preLoaderRoute: typeof AuthenticatedComplaintsIdRouteImport
      parentRoute: typeof AuthenticatedComplaintsRoute
    }
    '/_authenticated/applications/$id': {
      id: '/_authenticated/applications/$id'
      path: '/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof AuthenticatedApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedApplicationsRoute
    }
    '/_authenticated/portal/applications/$id': {
      id: '/_authenticated/portal/applications/$id'
      path: '/applications/$id'
      fullPath: '/portal/applications/$id'
      preLoaderRoute: typeof AuthenticatedPortalApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
  }
}

interface AuthenticatedApplicationsRouteChildren {
  AuthenticatedApplicationsIdRoute: typeof AuthenticatedApplicationsIdRoute
  AuthenticatedApplicationsIndexRoute: typeof AuthenticatedApplicationsIndexRoute
}

const AuthenticatedApplicationsRouteChildren: AuthenticatedApplicationsRouteChildren =
  {
    AuthenticatedApplicationsIdRoute: AuthenticatedApplicationsIdRoute,
    AuthenticatedApplicationsIndexRoute: AuthenticatedApplicationsIndexRoute,
  }

const AuthenticatedApplicationsRouteWithChildren =
  AuthenticatedApplicationsRoute._addFileChildren(
    AuthenticatedApplicationsRouteChildren,
  )

interface AuthenticatedComplaintsRouteChildren {
  AuthenticatedComplaintsIdRoute: typeof AuthenticatedComplaintsIdRoute
  AuthenticatedComplaintsIndexRoute: typeof AuthenticatedComplaintsIndexRoute
}

const AuthenticatedComplaintsRouteChildren: AuthenticatedComplaintsRouteChildren =
  {
    AuthenticatedComplaintsIdRoute: AuthenticatedComplaintsIdRoute,
    AuthenticatedComplaintsIndexRoute: AuthenticatedComplaintsIndexRoute,
  }

const AuthenticatedComplaintsRouteWithChildren =
  AuthenticatedComplaintsRoute._addFileChildren(
    AuthenticatedComplaintsRouteChildren,
  )

interface AuthenticatedMaintenanceRouteChildren {
  AuthenticatedMaintenanceIdRoute: typeof AuthenticatedMaintenanceIdRoute
  AuthenticatedMaintenanceIndexRoute: typeof AuthenticatedMaintenanceIndexRoute
}

const AuthenticatedMaintenanceRouteChildren: AuthenticatedMaintenanceRouteChildren =
  {
    AuthenticatedMaintenanceIdRoute: AuthenticatedMaintenanceIdRoute,
    AuthenticatedMaintenanceIndexRoute: AuthenticatedMaintenanceIndexRoute,
  }

const AuthenticatedMaintenanceRouteWithChildren =
  AuthenticatedMaintenanceRoute._addFileChildren(
    AuthenticatedMaintenanceRouteChildren,
  )

interface AuthenticatedPaymentsRouteChildren {
  AuthenticatedPaymentsIdRoute: typeof AuthenticatedPaymentsIdRoute
  AuthenticatedPaymentsIndexRoute: typeof AuthenticatedPaymentsIndexRoute
}

const AuthenticatedPaymentsRouteChildren: AuthenticatedPaymentsRouteChildren = {
  AuthenticatedPaymentsIdRoute: AuthenticatedPaymentsIdRoute,
  AuthenticatedPaymentsIndexRoute: AuthenticatedPaymentsIndexRoute,
}

const AuthenticatedPaymentsRouteWithChildren =
  AuthenticatedPaymentsRoute._addFileChildren(
    AuthenticatedPaymentsRouteChildren,
  )

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalProfileRoute: typeof AuthenticatedPortalProfileRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedPortalApplicationsIdRoute: typeof AuthenticatedPortalApplicationsIdRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalProfileRoute: AuthenticatedPortalProfileRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  AuthenticatedPortalApplicationsIdRoute:
    AuthenticatedPortalApplicationsIdRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedPropertiesRouteChildren {
  AuthenticatedPropertiesIdRoute: typeof AuthenticatedPropertiesIdRoute
  AuthenticatedPropertiesIndexRoute: typeof AuthenticatedPropertiesIndexRoute
}

const AuthenticatedPropertiesRouteChildren: AuthenticatedPropertiesRouteChildren =
  {
    AuthenticatedPropertiesIdRoute: AuthenticatedPropertiesIdRoute,
    AuthenticatedPropertiesIndexRoute: AuthenticatedPropertiesIndexRoute,
  }

const AuthenticatedPropertiesRouteWithChildren =
  AuthenticatedPropertiesRoute._addFileChildren(
    AuthenticatedPropertiesRouteChildren,
  )

interface AuthenticatedTenantsRouteChildren {
  AuthenticatedTenantsIdRoute: typeof AuthenticatedTenantsIdRoute
  AuthenticatedTenantsIndexRoute: typeof AuthenticatedTenantsIndexRoute
}

const AuthenticatedTenantsRouteChildren: AuthenticatedTenantsRouteChildren = {
  AuthenticatedTenantsIdRoute: AuthenticatedTenantsIdRoute,
  AuthenticatedTenantsIndexRoute: AuthenticatedTenantsIndexRoute,
}

const AuthenticatedTenantsRouteWithChildren =
  AuthenticatedTenantsRoute._addFileChildren(AuthenticatedTenantsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRouteWithChildren
  AuthenticatedComplaintsRoute: typeof AuthenticatedComplaintsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRouteWithChildren
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
  AuthenticatedPropertiesRoute: typeof AuthenticatedPropertiesRouteWithChildren
  AuthenticatedRenewalsRoute: typeof AuthenticatedRenewalsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTenantsRoute: typeof AuthenticatedTenantsRouteWithChildren
  AuthenticatedViewingsRoute: typeof AuthenticatedViewingsRoute
  AuthenticatedPeopleIdRoute: typeof AuthenticatedPeopleIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRouteWithChildren,
  AuthenticatedComplaintsRoute: AuthenticatedComplaintsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRouteWithChildren,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
  AuthenticatedPropertiesRoute: AuthenticatedPropertiesRouteWithChildren,
  AuthenticatedRenewalsRoute: AuthenticatedRenewalsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTenantsRoute: AuthenticatedTenantsRouteWithChildren,
  AuthenticatedViewingsRoute: AuthenticatedViewingsRoute,
  AuthenticatedPeopleIdRoute: AuthenticatedPeopleIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ListingsRouteChildren {
  ListingsIdRoute: typeof ListingsIdRoute
}

const ListingsRouteChildren: ListingsRouteChildren = {
  ListingsIdRoute: ListingsIdRoute,
}

const ListingsRouteWithChildren = ListingsRoute._addFileChildren(
  ListingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ListingsRoute: ListingsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
