export const TEMPLATE_VARIABLES_HELP = [
  { key: "agency_name", description: "Agency display name" },
  { key: "legal_name", description: "Agency legal entity name" },
  { key: "rera_number", description: "RERA registration number" },
  { key: "tenant_name", description: "Tenant full name" },
  { key: "tenant_email", description: "Tenant email" },
  { key: "tenant_emirates_id", description: "Tenant Emirates ID" },
  { key: "property_title", description: "Property title" },
  { key: "property_community", description: "Property community" },
  { key: "property_unit", description: "Building / unit" },
  { key: "offer_amount", description: "Formatted offer / rent amount" },
  { key: "security_deposit", description: "Security deposit amount" },
  { key: "cheques", description: "Number of cheques" },
  { key: "lease_start", description: "Lease start date" },
  { key: "lease_end", description: "Lease end date" },
  { key: "amount", description: "Payment amount" },
  { key: "due_date", description: "Payment due date" },
  { key: "status", description: "Application or ticket status" },
  { key: "viewing_date", description: "Viewing date/time" },
  { key: "portal_url", description: "Link to tenant portal" },
  { key: "today", description: "Today's date" },
] as const;
