/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AdminSiteRouteImport } from './routes/admin.site'
import { Route as AdminPrinciplesRouteImport } from './routes/admin.principles'
import { Route as AdminPortfolioRouteImport } from './routes/admin.portfolio'
import { Route as AdminPerspectiveRouteImport } from './routes/admin.perspective'
import { Route as AdminNavigationRouteImport } from './routes/admin.navigation'
import { Route as AdminLogosRouteImport } from './routes/admin.logos'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminHeroRouteImport } from './routes/admin.hero'
import { Route as AdminFooterRouteImport } from './routes/admin.footer'
import { Route as AdminCtaRouteImport } from './routes/admin.cta'
import { Route as AdminApproachRouteImport } from './routes/admin.approach'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteRoute = AdminSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrinciplesRoute = AdminPrinciplesRouteImport.update({
  id: '/principles',
  path: '/principles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPortfolioRoute = AdminPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerspectiveRoute = AdminPerspectiveRouteImport.update({
  id: '/perspective',
  path: '/perspective',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogosRoute = AdminLogosRouteImport.update({
  id: '/logos',
  path: '/logos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFooterRoute = AdminFooterRouteImport.update({
  id: '/footer',
  path: '/footer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCtaRoute = AdminCtaRouteImport.update({
  id: '/cta',
  path: '/cta',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApproachRoute = AdminApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/approach': typeof AdminApproachRoute
  '/admin/cta': typeof AdminCtaRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logos': typeof AdminLogosRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/perspective': typeof AdminPerspectiveRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/principles': typeof AdminPrinciplesRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/approach': typeof AdminApproachRoute
  '/admin/cta': typeof AdminCtaRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logos': typeof AdminLogosRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/perspective': typeof AdminPerspectiveRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/principles': typeof AdminPrinciplesRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/approach': typeof AdminApproachRoute
  '/admin/cta': typeof AdminCtaRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logos': typeof AdminLogosRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/perspective': typeof AdminPerspectiveRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/principles': typeof AdminPrinciplesRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/approach'
    | '/admin/cta'
    | '/admin/footer'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/logos'
    | '/admin/navigation'
    | '/admin/perspective'
    | '/admin/portfolio'
    | '/admin/principles'
    | '/admin/site'
    | '/admin/submissions'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/approach'
    | '/admin/cta'
    | '/admin/footer'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/logos'
    | '/admin/navigation'
    | '/admin/perspective'
    | '/admin/portfolio'
    | '/admin/principles'
    | '/admin/site'
    | '/admin/submissions'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/approach'
    | '/admin/cta'
    | '/admin/footer'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/logos'
    | '/admin/navigation'
    | '/admin/perspective'
    | '/admin/portfolio'
    | '/admin/principles'
    | '/admin/site'
    | '/admin/submissions'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site': {
      id: '/admin/site'
      path: '/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AdminSiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/principles': {
      id: '/admin/principles'
      path: '/principles'
      fullPath: '/admin/principles'
      preLoaderRoute: typeof AdminPrinciplesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/portfolio': {
      id: '/admin/portfolio'
      path: '/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AdminPortfolioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/perspective': {
      id: '/admin/perspective'
      path: '/perspective'
      fullPath: '/admin/perspective'
      preLoaderRoute: typeof AdminPerspectiveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logos': {
      id: '/admin/logos'
      path: '/logos'
      fullPath: '/admin/logos'
      preLoaderRoute: typeof AdminLogosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/footer': {
      id: '/admin/footer'
      path: '/footer'
      fullPath: '/admin/footer'
      preLoaderRoute: typeof AdminFooterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cta': {
      id: '/admin/cta'
      path: '/cta'
      fullPath: '/admin/cta'
      preLoaderRoute: typeof AdminCtaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approach': {
      id: '/admin/approach'
      path: '/approach'
      fullPath: '/admin/approach'
      preLoaderRoute: typeof AdminApproachRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApproachRoute: typeof AdminApproachRoute
  AdminCtaRoute: typeof AdminCtaRoute
  AdminFooterRoute: typeof AdminFooterRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLogosRoute: typeof AdminLogosRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminPerspectiveRoute: typeof AdminPerspectiveRoute
  AdminPortfolioRoute: typeof AdminPortfolioRoute
  AdminPrinciplesRoute: typeof AdminPrinciplesRoute
  AdminSiteRoute: typeof AdminSiteRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApproachRoute: AdminApproachRoute,
  AdminCtaRoute: AdminCtaRoute,
  AdminFooterRoute: AdminFooterRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLogosRoute: AdminLogosRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminPerspectiveRoute: AdminPerspectiveRoute,
  AdminPortfolioRoute: AdminPortfolioRoute,
  AdminPrinciplesRoute: AdminPrinciplesRoute,
  AdminSiteRoute: AdminSiteRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
