/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSubmissionsRouteImport } from './routes/admin/submissions'
import { Route as AdminSiteRouteImport } from './routes/admin/site'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminSectionsRouteImport } from './routes/admin/sections'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminProcessRouteImport } from './routes/admin/process'
import { Route as AdminNavigationRouteImport } from './routes/admin/navigation'
import { Route as AdminMetricsRouteImport } from './routes/admin/metrics'
import { Route as AdminMapRouteImport } from './routes/admin/map'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminHeroRouteImport } from './routes/admin/hero'
import { Route as AdminFooterRouteImport } from './routes/admin/footer'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteRoute = AdminSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectionsRoute = AdminSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProcessRoute = AdminProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMetricsRoute = AdminMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFooterRoute = AdminFooterRouteImport.update({
  id: '/footer',
  path: '/footer',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/footer': typeof AdminFooterRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/process': typeof AdminProcessRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/process': typeof AdminProcessRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/footer': typeof AdminFooterRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/process': typeof AdminProcessRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/footer'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/map'
    | '/admin/metrics'
    | '/admin/navigation'
    | '/admin/process'
    | '/admin/projects'
    | '/admin/sections'
    | '/admin/services'
    | '/admin/site'
    | '/admin/submissions'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/footer'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/map'
    | '/admin/metrics'
    | '/admin/navigation'
    | '/admin/process'
    | '/admin/projects'
    | '/admin/sections'
    | '/admin/services'
    | '/admin/site'
    | '/admin/submissions'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/footer'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/map'
    | '/admin/metrics'
    | '/admin/navigation'
    | '/admin/process'
    | '/admin/projects'
    | '/admin/sections'
    | '/admin/services'
    | '/admin/site'
    | '/admin/submissions'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site': {
      id: '/admin/site'
      path: '/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AdminSiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sections': {
      id: '/admin/sections'
      path: '/sections'
      fullPath: '/admin/sections'
      preLoaderRoute: typeof AdminSectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/process': {
      id: '/admin/process'
      path: '/process'
      fullPath: '/admin/process'
      preLoaderRoute: typeof AdminProcessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/metrics': {
      id: '/admin/metrics'
      path: '/metrics'
      fullPath: '/admin/metrics'
      preLoaderRoute: typeof AdminMetricsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/footer': {
      id: '/admin/footer'
      path: '/footer'
      fullPath: '/admin/footer'
      preLoaderRoute: typeof AdminFooterRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminFooterRoute: typeof AdminFooterRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMapRoute: typeof AdminMapRoute
  AdminMetricsRoute: typeof AdminMetricsRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminProcessRoute: typeof AdminProcessRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSectionsRoute: typeof AdminSectionsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSiteRoute: typeof AdminSiteRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFooterRoute: AdminFooterRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMapRoute: AdminMapRoute,
  AdminMetricsRoute: AdminMetricsRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminProcessRoute: AdminProcessRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSectionsRoute: AdminSectionsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSiteRoute: AdminSiteRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
