/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWalletsIndexRouteImport } from './routes/api/wallets/index'
import { Route as ApiTransactionsIndexRouteImport } from './routes/api/transactions/index'
import { Route as ApiCardsIndexRouteImport } from './routes/api/cards/index'
import { Route as ApiDashboardOverviewRouteImport } from './routes/api/dashboard/overview'
import { Route as ApiUserProfileIndexRouteImport } from './routes/api/user/profile/index'
import { Route as ApiAnalyticsIncomeIndexRouteImport } from './routes/api/analytics/income/index'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletsIndexRoute = ApiWalletsIndexRouteImport.update({
  id: '/api/wallets/',
  path: '/api/wallets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransactionsIndexRoute = ApiTransactionsIndexRouteImport.update({
  id: '/api/transactions/',
  path: '/api/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCardsIndexRoute = ApiCardsIndexRouteImport.update({
  id: '/api/cards/',
  path: '/api/cards/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardOverviewRoute = ApiDashboardOverviewRouteImport.update({
  id: '/api/dashboard/overview',
  path: '/api/dashboard/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserProfileIndexRoute = ApiUserProfileIndexRouteImport.update({
  id: '/api/user/profile/',
  path: '/api/user/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsIncomeIndexRoute = ApiAnalyticsIncomeIndexRouteImport.update({
  id: '/api/analytics/income/',
  path: '/api/analytics/income/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/manage': typeof ManageRoute
  '/program': typeof ProgramRoute
  '/reports': typeof ReportsRoute
  '/api/dashboard/overview': typeof ApiDashboardOverviewRoute
  '/api/cards/': typeof ApiCardsIndexRoute
  '/api/transactions/': typeof ApiTransactionsIndexRoute
  '/api/wallets/': typeof ApiWalletsIndexRoute
  '/api/analytics/income/': typeof ApiAnalyticsIncomeIndexRoute
  '/api/user/profile/': typeof ApiUserProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/manage': typeof ManageRoute
  '/program': typeof ProgramRoute
  '/reports': typeof ReportsRoute
  '/api/dashboard/overview': typeof ApiDashboardOverviewRoute
  '/api/cards': typeof ApiCardsIndexRoute
  '/api/transactions': typeof ApiTransactionsIndexRoute
  '/api/wallets': typeof ApiWalletsIndexRoute
  '/api/analytics/income': typeof ApiAnalyticsIncomeIndexRoute
  '/api/user/profile': typeof ApiUserProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/manage': typeof ManageRoute
  '/program': typeof ProgramRoute
  '/reports': typeof ReportsRoute
  '/api/dashboard/overview': typeof ApiDashboardOverviewRoute
  '/api/cards/': typeof ApiCardsIndexRoute
  '/api/transactions/': typeof ApiTransactionsIndexRoute
  '/api/wallets/': typeof ApiWalletsIndexRoute
  '/api/analytics/income/': typeof ApiAnalyticsIncomeIndexRoute
  '/api/user/profile/': typeof ApiUserProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/activity'
    | '/manage'
    | '/program'
    | '/reports'
    | '/api/dashboard/overview'
    | '/api/cards/'
    | '/api/transactions/'
    | '/api/wallets/'
    | '/api/analytics/income/'
    | '/api/user/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/activity'
    | '/manage'
    | '/program'
    | '/reports'
    | '/api/dashboard/overview'
    | '/api/cards'
    | '/api/transactions'
    | '/api/wallets'
    | '/api/analytics/income'
    | '/api/user/profile'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/activity'
    | '/manage'
    | '/program'
    | '/reports'
    | '/api/dashboard/overview'
    | '/api/cards/'
    | '/api/transactions/'
    | '/api/wallets/'
    | '/api/analytics/income/'
    | '/api/user/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ActivityRoute: typeof ActivityRoute
  ManageRoute: typeof ManageRoute
  ProgramRoute: typeof ProgramRoute
  ReportsRoute: typeof ReportsRoute
  ApiDashboardOverviewRoute: typeof ApiDashboardOverviewRoute
  ApiCardsIndexRoute: typeof ApiCardsIndexRoute
  ApiTransactionsIndexRoute: typeof ApiTransactionsIndexRoute
  ApiWalletsIndexRoute: typeof ApiWalletsIndexRoute
  ApiAnalyticsIncomeIndexRoute: typeof ApiAnalyticsIncomeIndexRoute
  ApiUserProfileIndexRoute: typeof ApiUserProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallets/': {
      id: '/api/wallets/'
      path: '/api/wallets'
      fullPath: '/api/wallets/'
      preLoaderRoute: typeof ApiWalletsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions/': {
      id: '/api/transactions/'
      path: '/api/transactions'
      fullPath: '/api/transactions/'
      preLoaderRoute: typeof ApiTransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cards/': {
      id: '/api/cards/'
      path: '/api/cards'
      fullPath: '/api/cards/'
      preLoaderRoute: typeof ApiCardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/overview': {
      id: '/api/dashboard/overview'
      path: '/api/dashboard/overview'
      fullPath: '/api/dashboard/overview'
      preLoaderRoute: typeof ApiDashboardOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/profile/': {
      id: '/api/user/profile/'
      path: '/api/user/profile'
      fullPath: '/api/user/profile/'
      preLoaderRoute: typeof ApiUserProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics/income/': {
      id: '/api/analytics/income/'
      path: '/api/analytics/income'
      fullPath: '/api/analytics/income/'
      preLoaderRoute: typeof ApiAnalyticsIncomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ActivityRoute: ActivityRoute,
  ManageRoute: ManageRoute,
  ProgramRoute: ProgramRoute,
  ReportsRoute: ReportsRoute,
  ApiDashboardOverviewRoute: ApiDashboardOverviewRoute,
  ApiCardsIndexRoute: ApiCardsIndexRoute,
  ApiTransactionsIndexRoute: ApiTransactionsIndexRoute,
  ApiWalletsIndexRoute: ApiWalletsIndexRoute,
  ApiAnalyticsIncomeIndexRoute: ApiAnalyticsIncomeIndexRoute,
  ApiUserProfileIndexRoute: ApiUserProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
