/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminTestimonialsRouteImport } from './routes/admin/testimonials'
import { Route as AdminTeamRouteImport } from './routes/admin/team'
import { Route as AdminSubmissionsRouteImport } from './routes/admin/submissions'
import { Route as AdminSiteRouteImport } from './routes/admin/site'
import { Route as AdminPropertiesRouteImport } from './routes/admin/properties'
import { Route as AdminProcessRouteImport } from './routes/admin/process'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFaqsRouteImport } from './routes/admin/faqs'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSiteRoute = AdminSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPropertiesRoute = AdminPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProcessRoute = AdminProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/process': typeof AdminProcessRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/process': typeof AdminProcessRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/process': typeof AdminProcessRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/faqs'
    | '/admin/login'
    | '/admin/process'
    | '/admin/properties'
    | '/admin/site'
    | '/admin/submissions'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/faqs'
    | '/admin/login'
    | '/admin/process'
    | '/admin/properties'
    | '/admin/site'
    | '/admin/submissions'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/faqs'
    | '/admin/login'
    | '/admin/process'
    | '/admin/properties'
    | '/admin/site'
    | '/admin/submissions'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/site': {
      id: '/admin/site'
      path: '/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AdminSiteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/properties': {
      id: '/admin/properties'
      path: '/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AdminPropertiesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/process': {
      id: '/admin/process'
      path: '/process'
      fullPath: '/admin/process'
      preLoaderRoute: typeof AdminProcessRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProcessRoute: typeof AdminProcessRoute
  AdminPropertiesRoute: typeof AdminPropertiesRoute
  AdminSiteRoute: typeof AdminSiteRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminFaqsRoute: AdminFaqsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProcessRoute: AdminProcessRoute,
  AdminPropertiesRoute: AdminPropertiesRoute,
  AdminSiteRoute: AdminSiteRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
