/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkersRouteImport } from './routes/_app/workers'
import { Route as AppWarningLettersRouteImport } from './routes/_app/warning-letters'
import { Route as AppVisaTrackingRouteImport } from './routes/_app/visa-tracking'
import { Route as AppTransportRouteImport } from './routes/_app/transport'
import { Route as AppTimesheetsRouteImport } from './routes/_app/timesheets'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppProTasksRouteImport } from './routes/_app/pro-tasks'
import { Route as AppPortalRouteImport } from './routes/_app/portal'
import { Route as AppPlacementsRouteImport } from './routes/_app/placements'
import { Route as AppPayslipsRouteImport } from './routes/_app/payslips'
import { Route as AppPayrollRouteImport } from './routes/_app/payroll'
import { Route as AppMedicalRouteImport } from './routes/_app/medical'
import { Route as AppLeaveApprovalsRouteImport } from './routes/_app/leave-approvals'
import { Route as AppJobOrdersRouteImport } from './routes/_app/job-orders'
import { Route as AppIssuesRouteImport } from './routes/_app/issues'
import { Route as AppInvoicesRouteImport } from './routes/_app/invoices'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppIncidentsRouteImport } from './routes/_app/incidents'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppContractsRouteImport } from './routes/_app/contracts'
import { Route as AppCommunicationsRouteImport } from './routes/_app/communications'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppClientPortalRouteImport } from './routes/_app/client-portal'
import { Route as AppCandidatesRouteImport } from './routes/_app/candidates'
import { Route as AppAttendanceRouteImport } from './routes/_app/attendance'
import { Route as AppAssetsRouteImport } from './routes/_app/assets'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAirportPickupsRouteImport } from './routes/_app/airport-pickups'
import { Route as AppAgentsRouteImport } from './routes/_app/agents'
import { Route as AppAgentPortalRouteImport } from './routes/_app/agent-portal'
import { Route as AppAccommodationsRouteImport } from './routes/_app/accommodations'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminSettingsRouteImport } from './routes/_app/admin/settings'
import { Route as AppAdminBrandingRouteImport } from './routes/_app/admin/branding'
import { Route as AppAdminBanksRouteImport } from './routes/_app/admin/banks'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkersRoute = AppWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AppRoute,
} as any)
const AppWarningLettersRoute = AppWarningLettersRouteImport.update({
  id: '/warning-letters',
  path: '/warning-letters',
  getParentRoute: () => AppRoute,
} as any)
const AppVisaTrackingRoute = AppVisaTrackingRouteImport.update({
  id: '/visa-tracking',
  path: '/visa-tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppTransportRoute = AppTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AppRoute,
} as any)
const AppTimesheetsRoute = AppTimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProTasksRoute = AppProTasksRouteImport.update({
  id: '/pro-tasks',
  path: '/pro-tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalRoute = AppPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AppRoute,
} as any)
const AppPlacementsRoute = AppPlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => AppRoute,
} as any)
const AppPayslipsRoute = AppPayslipsRouteImport.update({
  id: '/payslips',
  path: '/payslips',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicalRoute = AppMedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveApprovalsRoute = AppLeaveApprovalsRouteImport.update({
  id: '/leave-approvals',
  path: '/leave-approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppJobOrdersRoute = AppJobOrdersRouteImport.update({
  id: '/job-orders',
  path: '/job-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppIssuesRoute = AppIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsRoute = AppContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunicationsRoute = AppCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppClientPortalRoute = AppClientPortalRouteImport.update({
  id: '/client-portal',
  path: '/client-portal',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesRoute = AppCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAirportPickupsRoute = AppAirportPickupsRouteImport.update({
  id: '/airport-pickups',
  path: '/airport-pickups',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentPortalRoute = AppAgentPortalRouteImport.update({
  id: '/agent-portal',
  path: '/agent-portal',
  getParentRoute: () => AppRoute,
} as any)
const AppAccommodationsRoute = AppAccommodationsRouteImport.update({
  id: '/accommodations',
  path: '/accommodations',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminBrandingRoute = AppAdminBrandingRouteImport.update({
  id: '/admin/branding',
  path: '/admin/branding',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminBanksRoute = AppAdminBanksRouteImport.update({
  id: '/admin/banks',
  path: '/admin/banks',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/accommodations': typeof AppAccommodationsRoute
  '/agent-portal': typeof AppAgentPortalRoute
  '/agents': typeof AppAgentsRoute
  '/airport-pickups': typeof AppAirportPickupsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/assets': typeof AppAssetsRoute
  '/attendance': typeof AppAttendanceRoute
  '/candidates': typeof AppCandidatesRoute
  '/client-portal': typeof AppClientPortalRoute
  '/clients': typeof AppClientsRoute
  '/communications': typeof AppCommunicationsRoute
  '/contracts': typeof AppContractsRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/incidents': typeof AppIncidentsRoute
  '/inventory': typeof AppInventoryRoute
  '/invoices': typeof AppInvoicesRoute
  '/issues': typeof AppIssuesRoute
  '/job-orders': typeof AppJobOrdersRoute
  '/leave-approvals': typeof AppLeaveApprovalsRoute
  '/medical': typeof AppMedicalRoute
  '/payroll': typeof AppPayrollRoute
  '/payslips': typeof AppPayslipsRoute
  '/placements': typeof AppPlacementsRoute
  '/portal': typeof AppPortalRoute
  '/pro-tasks': typeof AppProTasksRoute
  '/reports': typeof AppReportsRoute
  '/tasks': typeof AppTasksRoute
  '/timesheets': typeof AppTimesheetsRoute
  '/transport': typeof AppTransportRoute
  '/visa-tracking': typeof AppVisaTrackingRoute
  '/warning-letters': typeof AppWarningLettersRoute
  '/workers': typeof AppWorkersRoute
  '/admin/banks': typeof AppAdminBanksRoute
  '/admin/branding': typeof AppAdminBrandingRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/accommodations': typeof AppAccommodationsRoute
  '/agent-portal': typeof AppAgentPortalRoute
  '/agents': typeof AppAgentsRoute
  '/airport-pickups': typeof AppAirportPickupsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/assets': typeof AppAssetsRoute
  '/attendance': typeof AppAttendanceRoute
  '/candidates': typeof AppCandidatesRoute
  '/client-portal': typeof AppClientPortalRoute
  '/clients': typeof AppClientsRoute
  '/communications': typeof AppCommunicationsRoute
  '/contracts': typeof AppContractsRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/incidents': typeof AppIncidentsRoute
  '/inventory': typeof AppInventoryRoute
  '/invoices': typeof AppInvoicesRoute
  '/issues': typeof AppIssuesRoute
  '/job-orders': typeof AppJobOrdersRoute
  '/leave-approvals': typeof AppLeaveApprovalsRoute
  '/medical': typeof AppMedicalRoute
  '/payroll': typeof AppPayrollRoute
  '/payslips': typeof AppPayslipsRoute
  '/placements': typeof AppPlacementsRoute
  '/portal': typeof AppPortalRoute
  '/pro-tasks': typeof AppProTasksRoute
  '/reports': typeof AppReportsRoute
  '/tasks': typeof AppTasksRoute
  '/timesheets': typeof AppTimesheetsRoute
  '/transport': typeof AppTransportRoute
  '/visa-tracking': typeof AppVisaTrackingRoute
  '/warning-letters': typeof AppWarningLettersRoute
  '/workers': typeof AppWorkersRoute
  '/admin/banks': typeof AppAdminBanksRoute
  '/admin/branding': typeof AppAdminBrandingRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/accommodations': typeof AppAccommodationsRoute
  '/_app/agent-portal': typeof AppAgentPortalRoute
  '/_app/agents': typeof AppAgentsRoute
  '/_app/airport-pickups': typeof AppAirportPickupsRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/assets': typeof AppAssetsRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/candidates': typeof AppCandidatesRoute
  '/_app/client-portal': typeof AppClientPortalRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/communications': typeof AppCommunicationsRoute
  '/_app/contracts': typeof AppContractsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/incidents': typeof AppIncidentsRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/issues': typeof AppIssuesRoute
  '/_app/job-orders': typeof AppJobOrdersRoute
  '/_app/leave-approvals': typeof AppLeaveApprovalsRoute
  '/_app/medical': typeof AppMedicalRoute
  '/_app/payroll': typeof AppPayrollRoute
  '/_app/payslips': typeof AppPayslipsRoute
  '/_app/placements': typeof AppPlacementsRoute
  '/_app/portal': typeof AppPortalRoute
  '/_app/pro-tasks': typeof AppProTasksRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/timesheets': typeof AppTimesheetsRoute
  '/_app/transport': typeof AppTransportRoute
  '/_app/visa-tracking': typeof AppVisaTrackingRoute
  '/_app/warning-letters': typeof AppWarningLettersRoute
  '/_app/workers': typeof AppWorkersRoute
  '/_app/admin/banks': typeof AppAdminBanksRoute
  '/_app/admin/branding': typeof AppAdminBrandingRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/accommodations'
    | '/agent-portal'
    | '/agents'
    | '/airport-pickups'
    | '/analytics'
    | '/assets'
    | '/attendance'
    | '/candidates'
    | '/client-portal'
    | '/clients'
    | '/communications'
    | '/contracts'
    | '/dashboard'
    | '/documents'
    | '/incidents'
    | '/inventory'
    | '/invoices'
    | '/issues'
    | '/job-orders'
    | '/leave-approvals'
    | '/medical'
    | '/payroll'
    | '/payslips'
    | '/placements'
    | '/portal'
    | '/pro-tasks'
    | '/reports'
    | '/tasks'
    | '/timesheets'
    | '/transport'
    | '/visa-tracking'
    | '/warning-letters'
    | '/workers'
    | '/admin/banks'
    | '/admin/branding'
    | '/admin/settings'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/accommodations'
    | '/agent-portal'
    | '/agents'
    | '/airport-pickups'
    | '/analytics'
    | '/assets'
    | '/attendance'
    | '/candidates'
    | '/client-portal'
    | '/clients'
    | '/communications'
    | '/contracts'
    | '/dashboard'
    | '/documents'
    | '/incidents'
    | '/inventory'
    | '/invoices'
    | '/issues'
    | '/job-orders'
    | '/leave-approvals'
    | '/medical'
    | '/payroll'
    | '/payslips'
    | '/placements'
    | '/portal'
    | '/pro-tasks'
    | '/reports'
    | '/tasks'
    | '/timesheets'
    | '/transport'
    | '/visa-tracking'
    | '/warning-letters'
    | '/workers'
    | '/admin/banks'
    | '/admin/branding'
    | '/admin/settings'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/sitemap.xml'
    | '/_app/accommodations'
    | '/_app/agent-portal'
    | '/_app/agents'
    | '/_app/airport-pickups'
    | '/_app/analytics'
    | '/_app/assets'
    | '/_app/attendance'
    | '/_app/candidates'
    | '/_app/client-portal'
    | '/_app/clients'
    | '/_app/communications'
    | '/_app/contracts'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/incidents'
    | '/_app/inventory'
    | '/_app/invoices'
    | '/_app/issues'
    | '/_app/job-orders'
    | '/_app/leave-approvals'
    | '/_app/medical'
    | '/_app/payroll'
    | '/_app/payslips'
    | '/_app/placements'
    | '/_app/portal'
    | '/_app/pro-tasks'
    | '/_app/reports'
    | '/_app/tasks'
    | '/_app/timesheets'
    | '/_app/transport'
    | '/_app/visa-tracking'
    | '/_app/warning-letters'
    | '/_app/workers'
    | '/_app/admin/banks'
    | '/_app/admin/branding'
    | '/_app/admin/settings'
    | '/_app/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workers': {
      id: '/_app/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof AppWorkersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/warning-letters': {
      id: '/_app/warning-letters'
      path: '/warning-letters'
      fullPath: '/warning-letters'
      preLoaderRoute: typeof AppWarningLettersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visa-tracking': {
      id: '/_app/visa-tracking'
      path: '/visa-tracking'
      fullPath: '/visa-tracking'
      preLoaderRoute: typeof AppVisaTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transport': {
      id: '/_app/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof AppTransportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timesheets': {
      id: '/_app/timesheets'
      path: '/timesheets'
      fullPath: '/timesheets'
      preLoaderRoute: typeof AppTimesheetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pro-tasks': {
      id: '/_app/pro-tasks'
      path: '/pro-tasks'
      fullPath: '/pro-tasks'
      preLoaderRoute: typeof AppProTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portal': {
      id: '/_app/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AppPortalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/placements': {
      id: '/_app/placements'
      path: '/placements'
      fullPath: '/placements'
      preLoaderRoute: typeof AppPlacementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payslips': {
      id: '/_app/payslips'
      path: '/payslips'
      fullPath: '/payslips'
      preLoaderRoute: typeof AppPayslipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll': {
      id: '/_app/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medical': {
      id: '/_app/medical'
      path: '/medical'
      fullPath: '/medical'
      preLoaderRoute: typeof AppMedicalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave-approvals': {
      id: '/_app/leave-approvals'
      path: '/leave-approvals'
      fullPath: '/leave-approvals'
      preLoaderRoute: typeof AppLeaveApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/job-orders': {
      id: '/_app/job-orders'
      path: '/job-orders'
      fullPath: '/job-orders'
      preLoaderRoute: typeof AppJobOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/issues': {
      id: '/_app/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof AppIssuesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidents': {
      id: '/_app/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts': {
      id: '/_app/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AppContractsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communications': {
      id: '/_app/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof AppCommunicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/client-portal': {
      id: '/_app/client-portal'
      path: '/client-portal'
      fullPath: '/client-portal'
      preLoaderRoute: typeof AppClientPortalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidates': {
      id: '/_app/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof AppCandidatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets': {
      id: '/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/airport-pickups': {
      id: '/_app/airport-pickups'
      path: '/airport-pickups'
      fullPath: '/airport-pickups'
      preLoaderRoute: typeof AppAirportPickupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent-portal': {
      id: '/_app/agent-portal'
      path: '/agent-portal'
      fullPath: '/agent-portal'
      preLoaderRoute: typeof AppAgentPortalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accommodations': {
      id: '/_app/accommodations'
      path: '/accommodations'
      fullPath: '/accommodations'
      preLoaderRoute: typeof AppAccommodationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/branding': {
      id: '/_app/admin/branding'
      path: '/admin/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AppAdminBrandingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/banks': {
      id: '/_app/admin/banks'
      path: '/admin/banks'
      fullPath: '/admin/banks'
      preLoaderRoute: typeof AppAdminBanksRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccommodationsRoute: typeof AppAccommodationsRoute
  AppAgentPortalRoute: typeof AppAgentPortalRoute
  AppAgentsRoute: typeof AppAgentsRoute
  AppAirportPickupsRoute: typeof AppAirportPickupsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAssetsRoute: typeof AppAssetsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppCandidatesRoute: typeof AppCandidatesRoute
  AppClientPortalRoute: typeof AppClientPortalRoute
  AppClientsRoute: typeof AppClientsRoute
  AppCommunicationsRoute: typeof AppCommunicationsRoute
  AppContractsRoute: typeof AppContractsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppIncidentsRoute: typeof AppIncidentsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppIssuesRoute: typeof AppIssuesRoute
  AppJobOrdersRoute: typeof AppJobOrdersRoute
  AppLeaveApprovalsRoute: typeof AppLeaveApprovalsRoute
  AppMedicalRoute: typeof AppMedicalRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppPayslipsRoute: typeof AppPayslipsRoute
  AppPlacementsRoute: typeof AppPlacementsRoute
  AppPortalRoute: typeof AppPortalRoute
  AppProTasksRoute: typeof AppProTasksRoute
  AppReportsRoute: typeof AppReportsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTimesheetsRoute: typeof AppTimesheetsRoute
  AppTransportRoute: typeof AppTransportRoute
  AppVisaTrackingRoute: typeof AppVisaTrackingRoute
  AppWarningLettersRoute: typeof AppWarningLettersRoute
  AppWorkersRoute: typeof AppWorkersRoute
  AppAdminBanksRoute: typeof AppAdminBanksRoute
  AppAdminBrandingRoute: typeof AppAdminBrandingRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccommodationsRoute: AppAccommodationsRoute,
  AppAgentPortalRoute: AppAgentPortalRoute,
  AppAgentsRoute: AppAgentsRoute,
  AppAirportPickupsRoute: AppAirportPickupsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAssetsRoute: AppAssetsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppCandidatesRoute: AppCandidatesRoute,
  AppClientPortalRoute: AppClientPortalRoute,
  AppClientsRoute: AppClientsRoute,
  AppCommunicationsRoute: AppCommunicationsRoute,
  AppContractsRoute: AppContractsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppIncidentsRoute: AppIncidentsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppIssuesRoute: AppIssuesRoute,
  AppJobOrdersRoute: AppJobOrdersRoute,
  AppLeaveApprovalsRoute: AppLeaveApprovalsRoute,
  AppMedicalRoute: AppMedicalRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppPayslipsRoute: AppPayslipsRoute,
  AppPlacementsRoute: AppPlacementsRoute,
  AppPortalRoute: AppPortalRoute,
  AppProTasksRoute: AppProTasksRoute,
  AppReportsRoute: AppReportsRoute,
  AppTasksRoute: AppTasksRoute,
  AppTimesheetsRoute: AppTimesheetsRoute,
  AppTransportRoute: AppTransportRoute,
  AppVisaTrackingRoute: AppVisaTrackingRoute,
  AppWarningLettersRoute: AppWarningLettersRoute,
  AppWorkersRoute: AppWorkersRoute,
  AppAdminBanksRoute: AppAdminBanksRoute,
  AppAdminBrandingRoute: AppAdminBrandingRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
