/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LiveDemosRouteImport } from './routes/live-demos'
import { Route as FaviconDoticoRouteImport } from './routes/favicon[.]ico'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as ExperienceIndexRouteImport } from './routes/experience/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio/$slug'
import { Route as ISlugRouteImport } from './routes/i/$slug'
import { Route as ExperienceSlugRouteImport } from './routes/experience/$slug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSubmissionsRouteImport } from './routes/admin/submissions'
import { Route as AdminSkillsRouteImport } from './routes/admin/skills'
import { Route as AdminSiteRouteImport } from './routes/admin/site'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminMarketingRouteImport } from './routes/admin/marketing'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminHeroRouteImport } from './routes/admin/hero'
import { Route as AdminExperienceRouteImport } from './routes/admin/experience'
import { Route as DemosSlugIndexRouteImport } from './routes/demos/$slug/index'
import { Route as DemosSlugSplatRouteImport } from './routes/demos/$slug/$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveDemosRoute = LiveDemosRouteImport.update({
  id: '/live-demos',
  path: '/live-demos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconDoticoRoute = FaviconDoticoRouteImport.update({
  id: '/favicon.ico',
  path: '/favicon.ico',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceIndexRoute = ExperienceIndexRouteImport.update({
  id: '/experience/',
  path: '/experience/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ISlugRoute = ISlugRouteImport.update({
  id: '/i/$slug',
  path: '/i/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceSlugRoute = ExperienceSlugRouteImport.update({
  id: '/experience/$slug',
  path: '/experience/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSkillsRoute = AdminSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSiteRoute = AdminSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExperienceRoute = AdminExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DemosSlugIndexRoute = DemosSlugIndexRouteImport.update({
  id: '/demos/$slug/',
  path: '/demos/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosSlugSplatRoute = DemosSlugSplatRouteImport.update({
  id: '/demos/$slug/$',
  path: '/demos/$slug/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/live-demos': typeof LiveDemosRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/experience': typeof AdminExperienceRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/experience/$slug': typeof ExperienceSlugRoute
  '/i/$slug': typeof ISlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/experience/': typeof ExperienceIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/demos/$slug/$': typeof DemosSlugSplatRoute
  '/demos/$slug/': typeof DemosSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/live-demos': typeof LiveDemosRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/experience': typeof AdminExperienceRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/experience/$slug': typeof ExperienceSlugRoute
  '/i/$slug': typeof ISlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/experience': typeof ExperienceIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/demos/$slug/$': typeof DemosSlugSplatRoute
  '/demos/$slug': typeof DemosSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/live-demos': typeof LiveDemosRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/experience': typeof AdminExperienceRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/experience/$slug': typeof ExperienceSlugRoute
  '/i/$slug': typeof ISlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/experience/': typeof ExperienceIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/demos/$slug/$': typeof DemosSlugSplatRoute
  '/demos/$slug/': typeof DemosSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/certifications'
    | '/contact'
    | '/favicon.ico'
    | '/live-demos'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/experience'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/marketing'
    | '/admin/media'
    | '/admin/projects'
    | '/admin/site'
    | '/admin/skills'
    | '/admin/submissions'
    | '/admin/users'
    | '/experience/$slug'
    | '/i/$slug'
    | '/portfolio/$slug'
    | '/projects/$slug'
    | '/admin/'
    | '/experience/'
    | '/portfolio/'
    | '/projects/'
    | '/demos/$slug/$'
    | '/demos/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/certifications'
    | '/contact'
    | '/favicon.ico'
    | '/live-demos'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/experience'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/marketing'
    | '/admin/media'
    | '/admin/projects'
    | '/admin/site'
    | '/admin/skills'
    | '/admin/submissions'
    | '/admin/users'
    | '/experience/$slug'
    | '/i/$slug'
    | '/portfolio/$slug'
    | '/projects/$slug'
    | '/admin'
    | '/experience'
    | '/portfolio'
    | '/projects'
    | '/demos/$slug/$'
    | '/demos/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/certifications'
    | '/contact'
    | '/favicon.ico'
    | '/live-demos'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/experience'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/marketing'
    | '/admin/media'
    | '/admin/projects'
    | '/admin/site'
    | '/admin/skills'
    | '/admin/submissions'
    | '/admin/users'
    | '/experience/$slug'
    | '/i/$slug'
    | '/portfolio/$slug'
    | '/projects/$slug'
    | '/admin/'
    | '/experience/'
    | '/portfolio/'
    | '/projects/'
    | '/demos/$slug/$'
    | '/demos/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CertificationsRoute: typeof CertificationsRoute
  ContactRoute: typeof ContactRoute
  FaviconDoticoRoute: typeof FaviconDoticoRoute
  LiveDemosRoute: typeof LiveDemosRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ExperienceSlugRoute: typeof ExperienceSlugRoute
  ISlugRoute: typeof ISlugRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ExperienceIndexRoute: typeof ExperienceIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  DemosSlugSplatRoute: typeof DemosSlugSplatRoute
  DemosSlugIndexRoute: typeof DemosSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-demos': {
      id: '/live-demos'
      path: '/live-demos'
      fullPath: '/live-demos'
      preLoaderRoute: typeof LiveDemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon.ico': {
      id: '/favicon.ico'
      path: '/favicon.ico'
      fullPath: '/favicon.ico'
      preLoaderRoute: typeof FaviconDoticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/': {
      id: '/experience/'
      path: '/experience'
      fullPath: '/experience/'
      preLoaderRoute: typeof ExperienceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$slug': {
      id: '/i/$slug'
      path: '/i/$slug'
      fullPath: '/i/$slug'
      preLoaderRoute: typeof ISlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/$slug': {
      id: '/experience/$slug'
      path: '/experience/$slug'
      fullPath: '/experience/$slug'
      preLoaderRoute: typeof ExperienceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/skills': {
      id: '/admin/skills'
      path: '/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AdminSkillsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/site': {
      id: '/admin/site'
      path: '/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AdminSiteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/experience': {
      id: '/admin/experience'
      path: '/experience'
      fullPath: '/admin/experience'
      preLoaderRoute: typeof AdminExperienceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/demos/$slug/': {
      id: '/demos/$slug/'
      path: '/demos/$slug'
      fullPath: '/demos/$slug/'
      preLoaderRoute: typeof DemosSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/$slug/$': {
      id: '/demos/$slug/$'
      path: '/demos/$slug/$'
      fullPath: '/demos/$slug/$'
      preLoaderRoute: typeof DemosSlugSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminExperienceRoute: typeof AdminExperienceRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSiteRoute: typeof AdminSiteRoute
  AdminSkillsRoute: typeof AdminSkillsRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminExperienceRoute: AdminExperienceRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSiteRoute: AdminSiteRoute,
  AdminSkillsRoute: AdminSkillsRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CertificationsRoute: CertificationsRoute,
  ContactRoute: ContactRoute,
  FaviconDoticoRoute: FaviconDoticoRoute,
  LiveDemosRoute: LiveDemosRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ExperienceSlugRoute: ExperienceSlugRoute,
  ISlugRoute: ISlugRoute,
  PortfolioSlugRoute: PortfolioSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ExperienceIndexRoute: ExperienceIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  DemosSlugSplatRoute: DemosSlugSplatRoute,
  DemosSlugIndexRoute: DemosSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
