-- Seed high-intent Dubai SEO pages for /i/: service + location clusters

insert into public.marketing_pages (
  slug,
  title,
  eyebrow,
  description,
  body_html,
  sections,
  meta,
  intent_page,
  target_keyword,
  target_location,
  target_service,
  internal_links,
  published,
  sort_order
)
values
  (
    'lead-full-stack-developer-dubai',
    'Lead Full-Stack Developer in Dubai',
    'Dubai corporate systems',
    'Lead Full-Stack Developer in Dubai focused on corporate websites, CRM systems, dashboards, and automation workflows.',
    '<p>I build and optimize corporate-grade digital systems for businesses in Dubai, including CRM workflows, booking journeys, internal dashboards, and SEO-ready websites.</p>',
    '{"faq":[{"question":"Do you work with enterprise workflows?","answer":"Yes. I design and ship business-critical flows across CRM, operations, and web platforms."}]}'::jsonb,
    '{"seoTitle":"Lead Full-Stack Developer Dubai | Corporate Systems","seoDescription":"Lead Full-Stack Developer in Dubai for corporate websites, CRM systems, dashboards, and digital operations.","canonicalPath":"/i/lead-full-stack-developer-dubai"}'::jsonb,
    true,
    'Lead Full-Stack Developer Dubai',
    'Dubai, United Arab Emirates',
    'Corporate web systems and CRM development',
    '[{"label":"Portfolio case studies","href":"/portfolio"},{"label":"Experience in Dubai","href":"/experience"},{"label":"Contact for projects","href":"/contact"}]'::jsonb,
    true,
    10
  ),
  (
    'crm-developer-difc',
    'CRM Developer for DIFC Corporate Teams',
    'DIFC',
    'CRM developer support for DIFC-focused corporate teams needing automation, lead workflows, and reporting.',
    '<p>For finance and corporate teams in DIFC, I build CRM and automation workflows that improve speed, visibility, and conversion quality.</p>',
    '{}'::jsonb,
    '{"seoTitle":"CRM Developer DIFC Dubai","seoDescription":"CRM developer in DIFC for corporate workflow automation and reporting.","canonicalPath":"/i/crm-developer-difc"}'::jsonb,
    true,
    'CRM Developer DIFC',
    'DIFC, Dubai',
    'CRM automation',
    '[{"label":"See CRM-focused projects","href":"/portfolio"},{"label":"Discuss your use case","href":"/contact"}]'::jsonb,
    true,
    20
  ),
  (
    'corporate-web-developer-business-bay',
    'Corporate Web Developer in Business Bay',
    'Business Bay',
    'Corporate web development for Business Bay companies needing reliable, scalable, and SEO-ready web platforms.',
    '<p>I support Business Bay teams with high-performance web platforms tied to lead capture, CRM, and operational outcomes.</p>',
    '{}'::jsonb,
    '{"seoTitle":"Corporate Web Developer Business Bay Dubai","seoDescription":"Corporate web developer in Business Bay for SEO-ready websites and connected business systems.","canonicalPath":"/i/corporate-web-developer-business-bay"}'::jsonb,
    true,
    'Corporate Web Developer Business Bay',
    'Business Bay, Dubai',
    'Corporate websites',
    '[{"label":"Portfolio work","href":"/portfolio"},{"label":"Live demos","href":"/live-demos"},{"label":"Contact","href":"/contact"}]'::jsonb,
    true,
    30
  ),
  (
    'software-developer-dubai-internet-city',
    'Software Developer in Dubai Internet City',
    'Dubai Internet City',
    'Software and platform development for Dubai Internet City businesses: web apps, dashboards, and integrations.',
    '<p>I work with software and product teams in Dubai Internet City to ship robust full-stack features and production-ready systems.</p>',
    '{}'::jsonb,
    '{"seoTitle":"Software Developer Dubai Internet City","seoDescription":"Software developer in Dubai Internet City for full-stack delivery, integrations, and scalable systems.","canonicalPath":"/i/software-developer-dubai-internet-city"}'::jsonb,
    true,
    'Software Developer Dubai Internet City',
    'Dubai Internet City, Dubai',
    'Full-stack software delivery',
    '[{"label":"Technical experience","href":"/experience"},{"label":"Project portfolio","href":"/portfolio"}]'::jsonb,
    true,
    40
  ),
  (
    'business-systems-developer-dmcc-jlt',
    'Business Systems Developer in DMCC / JLT',
    'DMCC / JLT',
    'Business systems development in DMCC/JLT across dashboards, workflows, and operational automation.',
    '<p>I build business systems for DMCC/JLT companies, connecting internal workflows, dashboards, and data visibility.</p>',
    '{}'::jsonb,
    '{"seoTitle":"Business Systems Developer DMCC JLT Dubai","seoDescription":"Business systems developer in DMCC/JLT for internal dashboards, workflows, and automation.","canonicalPath":"/i/business-systems-developer-dmcc-jlt"}'::jsonb,
    true,
    'Business Systems Developer DMCC JLT',
    'DMCC / JLT, Dubai',
    'Business systems and dashboards',
    '[{"label":"View dashboard projects","href":"/portfolio"},{"label":"See live demos","href":"/live-demos"}]'::jsonb,
    true,
    50
  ),
  (
    'technical-seo-developer-dubai',
    'Technical SEO Developer in Dubai',
    'Technical SEO',
    'Technical SEO implementation for Dubai corporate websites: metadata, schema, crawlability, and internal linking.',
    '<p>I implement technical SEO foundations that improve discoverability: route metadata, sitemap coverage, structured data, and internal linking strategy.</p>',
    '{}'::jsonb,
    '{"seoTitle":"Technical SEO Developer Dubai","seoDescription":"Technical SEO developer in Dubai for metadata, schema, internal linking, and site architecture.","canonicalPath":"/i/technical-seo-developer-dubai"}'::jsonb,
    true,
    'Technical SEO Developer Dubai',
    'Dubai, United Arab Emirates',
    'Technical SEO',
    '[{"label":"Read about experience","href":"/experience"},{"label":"Explore portfolio","href":"/portfolio"},{"label":"Start a project","href":"/contact"}]'::jsonb,
    true,
    60
  )
on conflict (slug) do update
set
  title = excluded.title,
  eyebrow = excluded.eyebrow,
  description = excluded.description,
  body_html = excluded.body_html,
  sections = excluded.sections,
  meta = excluded.meta,
  intent_page = excluded.intent_page,
  target_keyword = excluded.target_keyword,
  target_location = excluded.target_location,
  target_service = excluded.target_service,
  internal_links = excluded.internal_links,
  published = excluded.published,
  sort_order = excluded.sort_order,
  updated_at = now();
